name: quran
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  conditional_builder_null_safety: ^0.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_launcher_icons: ^0.12.0
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.4
  get: ^4.6.5
  get_it: ^7.2.0
  http: ^0.13.5
  just_audio: ^0.9.32
  lottie: ^2.3.1
  path: ^1.8.2
  quickalert: ^1.0.1
  scroll_to_index: ^3.0.1
  shared_preferences: ^2.1.0
  sqflite: ^2.2.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/json/
    - assets/images/png/
    - assets/images/svg/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: Katib
      fonts:
        - asset: assets/fonts/kitab.ttf
